Dizajn faza 1
pfe-rs/zr-s-2024-slagalica pull request #1
Opened 2024-03-27 20:41 UTC by pixiliicious

2024-03-27 20:42 UTC, StefanTesmanovic approved these changes, later dismissed

2024-03-27 21:04 UTC, lazar2222 requested changes
![image](https://github.com/pfe-rs/zr-s-2024-slagalica/assets/10290790/d2049d8a-d807-4ca1-b0b2-fc4d58141802)
Obrisati nepotrebne klase.

- [X] tabla i dimenzija mogu da budu privatne i fali tip podataka za dimenziju
- [X] potom dodati gettere za tablu i dimenziju

- [ ] dodati konstruktor za tablu koji popunjava polja i staticki metod koji generise random resivu tablu

- [X] fali tip za smer u pomeri tastatura

- [X] mozda bi bilo bolje da se provera zove resena

- [X] povratne vrednosti metoda fale

- [X] resi nije deo ove faze, obrisati

- [X] potencijalno pomeriti samu proveru da li je resiva u odvojen metod

- [X] Mozda preimenovati TablaCrtanje u Igra

- [ ] umesto svojstva tabla treba dodati asocijaciju od TablaCrtanje do Tabla i to treba biti privatno sa getterom i setterom

- [X] nacrtaj tablu ne treba da ima argument vec koristi tablu koja je pridruzena objektu

- [ ] potencijalno dodati metodu koja obradjuje korisnicki unos u TablaCrtanje i metodu koja odigrava jednu rundu

- [ ] Zasto je crtaj tablu staticka

2024-03-27 21:33 UTC, djokjulapfe commented
Nemojte praviti PR za implementaciju pre PRa za dizajn.

2024-03-27 22:12 UTC, djokjulapfe commented
Izvinite, slučajno

2024-03-28 11:16 UTC, lazar2222 approved these changes

2024-03-28 11:17 UTC, merged