Kraj druge faze
pfe-rs/zr-s-2024-slagalica pull request #6
Opened 2024-03-28 21:51 UTC by StefanTesmanovic

2024-03-28 21:52 UTC, pixiliicious approved these changes, later dismissed
kul

2024-03-28 22:12 UTC, lazar2222 commented
Checks failed, popravite testove

2024-03-29 10:16 UTC, lazar2222 requested changes
Istestirati cuvanje i ucitavanje igre, ja sam probao i nesto mi ne radi.

Sto znaci da treba dodati i testove za ucitavanje i cuvanje.

2024-03-29 11:33 UTC, lazar2222 requested changes
Ostalo je dobro, samo jedan komentar i dodati testove za cuvanje i ucitavanje.

2024-03-29 11:33 UTC, lazar2222 commented on klase.py
> +        else: self.pocniIgru()
Ovo ne radi kako treba, istestirati

2024-03-29 23:11 UTC, lazar2222 commented
Puca program kad ne unesem ni new ni old

2024-03-30 15:28 UTC, lazar2222 approved these changes
To je to, bravo! :shipit:

2024-03-30 15:28 UTC, merged